name       : asciidoctor
version    : 2.0.20
release    : 8
source     :
    - https://github.com/asciidoctor/asciidoctor/archive/refs/tags/v2.0.20.tar.gz : e38d8e15e0bf0f28811e35e3e24ca30b9f5424669ffd9e8e4c208b21f45dbdea
homepage   : https://asciidoctor.org/
license    : MIT
component  : programming.tools
summary    : A fast text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
description: |
    A fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
builddeps  :
    - pkgconfig(ruby-3.2)
rundeps    :
    - ruby
build      : |
    %gem_build
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
    rm -rf $installdir/$geminstalldir/gems/asciidoctor-*/{CHANGELOG.adoc,LICENSE,README*}
