name       : asciidoctor
version    : 2.0.13
release    : 2
source     :
    - https://github.com/asciidoctor/asciidoctor/archive/refs/tags/v2.0.13.tar.gz : 4812dd15bb71b3ae8351e8e3c2df4528c7c40dd97ef1954a56442b56b59019a6
license    : MIT
component  : programming.tools
summary    : A fast text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
description: |
    A fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
build      : |
    %gem_build
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
    rm -rf $installdir/$geminstalldir/gems/asciidoctor-*/{CHANGELOG.adoc,LICENSE,README*}
