name       : asciidoctor
version    : 2.0.12
release    : 1
source     :
    - https://github.com/asciidoctor/asciidoctor/archive/v2.0.12.tar.gz : cd98047c68bf1074a7058b174c93a64f2bd39c2f33941398f6889c562ed5bce8
license    : MIT
component  : programming.tools
summary    : A fast text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
description: |
    A fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
build      : |
    %gem_build
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
    rm -rf $installdir/$geminstalldir/gems/asciidoctor-*/{CHANGELOG.adoc,LICENSE,README*}
